# Generated by Django 4.2.6 on 2023-10-15 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qusasa", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
