# Generated by Django 4.2.6 on 2024-03-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qusasa", "0002_inquiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileanalysishistory",
            name="user",
        ),
        migrations.RemoveField(
            model_name="topictrendanalysishistory",
            name="user",
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="date_resolved",
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name="PostAnalysisHistory",
        ),
        migrations.DeleteModel(
            name="ProfileAnalysisHistory",
        ),
        migrations.DeleteModel(
            name="TopicTrendAnalysisHistory",
        ),
    ]
