# Generated by Django 4.2.6 on 2023-10-15 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qusasa", "0002_remove_customuser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
