# Generated by Django 4.2.6 on 2024-03-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qusasa", "0003_remove_profileanalysishistory_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="date_resolved",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
