# Generated by Django 4.2.6 on 2023-10-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qusasa", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_confirmation_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
