# Generated by Django 4.2.6 on 2023-12-01 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qusasa", "0004_customuser_email_confirmation_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicAnalysisHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_query", models.CharField(max_length=200)),
                ("order", models.CharField(max_length=50)),
                ("region_code", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
