# Generated by Django 4.2.6 on 2024-02-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qusasa', '0008_profileanalysishistory_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
