# Generated by Django 5.0.1 on 2024-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qusasa', '0010_topictrendanalysishistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(default='Resolved', max_length=2048),
            preserve_default=False,
        ),
    ]
